# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch # push 的时候触发
  push:
    branches: [ main ]
  # 每周二触发
  schedule:
    - cron: '0 21 * * 2'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  获取照片 Job1
  social:
    timeout-minutes: 10
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it # 获取代码
      - uses: actions/checkout@v4
      
      # 设置 node 环境
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      # 添加依赖
      - name: Install dependencies
        run: npm install

      # 生成文件
      - name: Generate README file
        run: node index.js

      # push 代码，需要自己的 Github token
      - name: Push new README.md
        uses: ad-m/github-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.AC_TOKEN }}
          BRANCH_NAME: ${{ github.main }}

  # 更新博客 Job2    
  blog:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: social


    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #   - name: Pull in dev.to posts
    #     uses: gautamkrishnar/blog-post-workflow@master
    #     with:
    #       feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"


    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Playwright
        uses: microsoft/playwright-github-action@v1
      - name: Firefox
        run: npx playwright install firefox
      # GitHub Actions unfortunately does not support retries;
      # this is a cumbersome method of retrying twice in case of errors:
      - name: Feed
        run: npx feed-me-up-scotty || npx feed-me-up-scotty || npx feed-me-up-scotty

      - name: Deploy to GitHub Pages
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote add gh-pages-remote https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git fetch --no-recurse-submodules
          git worktree add ./gh-pages gh-pages
          cd gh-pages
          git rm -r .
          cp -r ../public/. .
          git add .
          git commit --message="Deploying to GitHub Pages from $GITHUB_SHA"
          git push gh-pages-remote gh-pages:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Print all 
        run: pwd

      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://littleggghost.github.io/littleggghost/funfacts.xml"
          # disable_item_validation: true
          # item_exec: "if (!post.title) post = null;" #to skip post that dont have title

      # - name: Metrics
      #   uses: lowlighter/metrics@latest
      #   with:
      #     # Your GitHub token
      #     # The following scopes are required:
      #     #  - public_access (default scope)
      #     # The following additional scopes may be required:
      #     #  - read:org      (for organization related metrics)
      #     #  - read:user     (for user related data)
      #     #  - read:packages (for some packages related data)
      #     #  - repo          (optional, if you want to include private repositories)
      #     token: ${{ secrets.AC_TOKEN }}

      #     # Options
      #     user: littleggghost
      #     template: classic
      #     base: header, activity, community, repositories, metadata
      #     config_timezone: Asia/Shanghai
      #     plugin_posts: yes
      #     plugin_posts_covers: yes
      #     plugin_posts_limit: 6
      #     plugin_posts_source: "https://littleggghost.github.io/littleggghost/funfacts.xml"
      #     plugin_posts_user: .user.login

      - name: Plugin Metrics Posts
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-blog.svg
          token: ${{ secrets.AC_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_posts: yes
          plugin_posts_source: https://littleggghost.github.io/littleggghost/funfacts.xml
          base: ""


    # steps:
    #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #   - uses: actions/checkout@v4
      
    #   # 使用 docker compose 部署 rsshub
    #   - name: Start containers
    #     run: docker-compose -f "docker-compose.yml" up -d --build

    #   - name: Install python module
    #     run: pip3 install --user bs4 datetime

    #   - name: run python
    #     run: python3 test.py

    #   - name: print
    #     run: cat feed.xml

    #   - name: Install node
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: 14.x

    #   - name: Install dependencies
    #     run: npm install
      
    #   # 将注释替换成更新博客链接
    #   - uses: gautamkrishnar/blog-post-workflow@master
    #     with:
    #       feed_list: "feed.xml"
          
    #   - name: Stop containers
    #     if: always()
    #     run: docker-compose -f "docker-compose.yml" down

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   - name: Setup Hugo
    #     uses: peaceiris/actions-hugo@v2
    #     with:
    #       hugo-version: 'latest'

    #   - name: Build
    #     run: hugo --minify

    #   - name: Deploy
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.AC_TOKEN }}
    #       publish_dir: ./public
